image: archlinux
packages:
  - rsync
sources:
  - git@git.sr.ht:~bentglasstube/tracker
environment:
  deploy: 'web@eatabrick.org:tracker.eatabrick.org'
secrets:
  - 7a7c0309-95bb-4107-9e42-96352295d661
tasks:
  - deploy: |
      cd tracker
      sshopts="ssh -o StrictHostKeyChecking=no"
      rsync --rsh="$sshopts" -arvz . "$deploy"/. --delete --exclude='.git/'
